[phases.setup]
nixPkgs = ["bun", "nodejs_20"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = [
  "bunx tsr generate",
  "tsc --noEmit",
  "vite build --sourcemap"
]

[start]
cmd = "bun run server.ts"
